export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  header: {
    background: 'rgba(255, 255, 255, 0.15)',
    backdropFilter: 'blur(10px)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.2)',
    padding: '20px',
    boxShadow: '0 4px 30px rgba(0, 0, 0, 0.1)',
  },
  headerContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    gap: '15px',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  logo: {
    width: '50px',
    height: '50px',
    background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
  },
  headerTitle: {
    color: 'white',
    fontSize: '28px',
    fontWeight: 'bold',
    margin: 0,
    textShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
  },
  headerSubtitle: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: '13px',
    margin: '2px 0 0 0',
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  clearButton: {
    background: 'rgba(239, 68, 68, 0.8)',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
  },
  exportButton: {
    background: 'rgba(16, 185, 129, 0.8)',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    backdropFilter: 'blur(10px)',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
  },
  messagesContainer: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '30px 20px',
  },
  messagesContent: {
    maxWidth: '1200px',
    margin: '0 auto',
  },
  emptyState: {
    textAlign: 'center' as const,
    marginTop: '100px',
  },
  emptyStateCard: {
    display: 'inline-block',
    padding: '50px',
    background: 'rgba(255, 255, 255, 0.95)',
    borderRadius: '30px',
    boxShadow: '0 10px 50px rgba(0, 0, 0, 0.2)',
  },
  emptyStateIcon: {
    fontSize: '80px',
    marginBottom: '20px',
  },
  emptyStateTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#333',
    margin: '10px 0',
  },
  emptyStateText: {
    fontSize: '15px',
    color: '#666',
    maxWidth: '400px',
    margin: '10px auto',
  },
  messageWrapper: {
    display: 'flex',
    marginBottom: '24px',
    animation: 'slideUp 0.4s ease-out',
  },
  messageWrapperUser: {
    justifyContent: 'flex-end',
  },
  messageWrapperAi: {
    justifyContent: 'flex-start',
  },
  messageContent: {
    display: 'flex',
    gap: '12px',
    maxWidth: '75%',
  },
  messageContentReverse: {
    flexDirection: 'row-reverse' as const,
  },
  avatar: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '22px',
    flexShrink: 0,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
  },
  avatarUser: {
    background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  },
  avatarAi: {
    background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
  bubble: {
    padding: '16px 20px',
    borderRadius: '20px',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.15)',
    transition: 'transform 0.2s ease',
    position: 'relative' as const,
  },
  bubbleUser: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    borderTopRightRadius: '5px',
  },
  bubbleAi: {
    background: 'rgba(255, 255, 255, 0.95)',
    color: '#333',
    borderTopLeftRadius: '5px',
  },
  bubbleHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  bubbleLabel: {
    fontSize: '11px',
    fontWeight: 'bold',
    margin: 0,
    opacity: 0.8,
  },
  timestamp: {
    fontSize: '10px',
    opacity: 0.6,
    fontWeight: 'normal',
    marginLeft: '8px',
  },
  bubbleText: {
    fontSize: '15px',
    lineHeight: '1.6',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    margin: 0,
  },
  errorBadge: {
    marginTop: '8px',
    padding: '8px 12px',
    background: 'rgba(239, 68, 68, 0.1)',
    borderRadius: '8px',
    fontSize: '12px',
    color: '#dc2626',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  statusBadge: {
    marginTop: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    opacity: 0.7,
  },
  loadingDots: {
    display: 'flex',
    gap: '5px',
    alignItems: 'center',
  },
  dot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  },
  inputContainer: {
    background: 'rgba(255, 255, 255, 0.15)',
    backdropFilter: 'blur(10px)',
    borderTop: '1px solid rgba(255, 255, 255, 0.2)',
    padding: '20px 25px',
    boxShadow: '0 -4px 30px rgba(0, 0, 0, 0.1)',
  },
  inputForm: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    gap: '15px',
    alignItems: 'flex-end',
  },
  textarea: {
    flex: 1,
    padding: '14px 20px',
    paddingRight: '80px',
    fontSize: '15px',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '16px',
    background: 'rgba(255, 255, 255, 0.95)',
    outline: 'none',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    fontFamily: 'inherit',
    resize: 'none' as const,
    minHeight: '52px',
    maxHeight: '200px',
    lineHeight: '1.5',
  },
  charCounter: {
    position: 'absolute' as const,
    bottom: '8px',
    right: '12px',
    pointerEvents: 'none' as const,
  },
  sendButton: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: 'white',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '16px',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.2)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
};
